services:
  dh_doctrine_audit.configuration:
    class: DH\DoctrineAuditBundle\AuditConfiguration
    arguments: ["%dh_doctrine_audit.configuration%", "@security.token_storage", "@request_stack"]
    public: true

  dh_doctrine_audit.event_subscriber.audit:
    class: DH\DoctrineAuditBundle\EventSubscriber\AuditSubscriber
    arguments: ["@dh_doctrine_audit.configuration"]
    tags:
      - { name: doctrine.event_subscriber, connection: default }
